# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0002_gamemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconnection',
            name='area1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='worldbuilder.Area', verbose_name='starting area'),
        ),
        migrations.AlterField(
            model_name='areaconnection',
            name='area2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='worldbuilder.Area', verbose_name='connected area'),
        ),
    ]
