# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0003_auto_20170627_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
