# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0004_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
