# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0005_auto_20170807_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbilityCheck',
        ),
        migrations.RemoveField(
            model_name='areaconnection',
            name='area1',
        ),
        migrations.RemoveField(
            model_name='areaconnection',
            name='area2',
        ),
        migrations.RemoveField(
            model_name='areafeature',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='campaign',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='worldbuilder.Campaign'),
        ),
        migrations.DeleteModel(
            name='AreaConnection',
        ),
        migrations.DeleteModel(
            name='AreaFeature',
        ),
    ]
