# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0006_auto_20170930_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='region',
        ),
        migrations.AlterField(
            model_name='area',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worldbuilder.Campaign'),
        ),
    ]
