# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0007_auto_20171004_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldbuilder.Campaign'),
        ),
        migrations.AddField(
            model_name='arearelationship',
            name='child_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_area', to='worldbuilder.Area'),
        ),
        migrations.AddField(
            model_name='arearelationship',
            name='parent_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_area', to='worldbuilder.Area'),
        ),
    ]
