# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0008_auto_20171005_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arearelationship',
            name='child_area',
        ),
        migrations.RemoveField(
            model_name='arearelationship',
            name='parent_area',
        ),
        migrations.RemoveField(
            model_name='region',
            name='campaign',
        ),
        migrations.AddField(
            model_name='area',
            name='parent_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worldbuilder.Area'),
        ),
        migrations.DeleteModel(
            name='AreaRelationship',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
