# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0011_auto_20171013_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='area',
            name='parent_area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
