# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0012_auto_20171013_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('code', models.CharField(max_length=32, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldbuilder.Campaign')),
                ('parent_area', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='worldbuilder.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
