# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilder', '0013_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='parent_area',
            new_name='parent',
        ),
    ]
